### ISSUE TITLE
This is not malware

### ISSUE THREAD

**Issue by Luamnoxu** [Pissandshittium/pissandshittium#126]
why
please fix this in the next update

**Comment by aggregate1166877** [comment]
:downthumbs:, we're trying to fuck ourselves implicitly, not _ex_ plicitly.

**Comment by Aikoyori** [comment]
this is not a malware

**Comment by Luamnoxu** [comment]
> :downthumbs:, we're trying to fuck ourselves implicitly, not _ex_ plicitly.

![image](https://github.com/Pissandshittium/pissandshittium/assets/87062000/7fa0af7b-d34c-4c6e-bcfa-ec6c7a7e6646)
