### ISSUE TITLE
invite me to your contributor team 

### ISSUE THREAD

**Issue by Vitalya-code** [Pissandshittium/pissandshittium#22]
invite me, because i know how to code in c and rust and assembly and cobol and i can help with implementing bugs because im quite good at it because im smart

**Comment by AdamFrack** [comment]
theaye serch ng fro scartch progamers

**Comment by Vitalya-code** [comment]
I am profesianal scratch developr ican do the job done!

**Comment by AdamFrack** [comment]
whn t 3 am pls go kall (kde call) th mr pissandshittium dnd ask for job
