### ISSUE TITLE
Make it closed source

### ISSUE THREAD

**Issue by WreckingBANG** [Pissandshittium/pissandshittium#25]
It is not a true bad browser if it is FOSS.

**Comment by AdamFrack** [comment]
this is a good browser dude

**Comment by Techman69** [comment]
Licence it under the nofucksgiven licence

**Comment by Aikoyori** [comment]
I'm sorry but all jokes aside OSS is pretty cool so I will leave it there

**Comment by WreckingBANG** [comment]
This was just a joke i love foss
