### ISSUE TITLE
my balls itch

### ISSUE THREAD

**Issue by Loomeh** [Pissandshittium/pissandshittium#39]
please help

**Comment by AdamFrack** [comment]
rewrite them in rust

**Comment by MacroHard-Winux** [comment]
I have the same problem and tried to rewrite by balls in rust, but issue still persist. Are they any other way to fix it?

**Comment by EvilGremlin** [comment]
You doing it wrong, you have to use emacs to rewrite them in rust, else it wont's work. You can try vim, but then it gotta be in haskel...

**Comment by s-liwka** [comment]
same issue here, anyone found a workaround?

**Comment by ghost** [comment]
Fixed in the v1337 beta

**Comment by MacroHard-Winux** [comment]
Oh I download the v1337 beta and it is now fixed thx
OP please close this issue
