### ISSUE TITLE
Feature request: add malware and spyware

### ISSUE THREAD

**Issue by Silverdev2482** [Pissandshittium/pissandshittium#40]
When using this high quality software I found myself having too much privacy, I asked for garbage not privacy friendly software. Maybe open a h.256 stream anyone can view?

**Comment by Aikoyori** [comment]
as much as that would be funny as shit i don't want it to be that malicious

**Comment by Silverdev2482** [comment]
Maybe there should be two versions of the browser, malicous, and non malicious.
