### ISSUE TITLE
My Computer turns on and starts Pissandshittium automatically every time I want to toilet

### ISSUE THREAD

**Issue by MacroHard-Winux** [Pissandshittium/pissandshittium#88]
# The problem
Every time I went to the toilet, all the computer that have the browser installed will automaticity start up, login in and starts pissandshittium. It is being a massive annoyance and now my electric bills are through the roof.

**Comment by ghost** [comment]
same problem on Windows 95

**Comment by Aikoyori** [comment]
Intended behaviour

**Comment by MacroHard-Winux** [comment]
Is it possible to at least add a switch to turn the feature on or off?

**Comment by ghost** [comment]
just dont go to the toilet

**Comment by MacroHard-Winux** [comment]
Oh wait I never thought of that, sorry :P
