### ISSUE TITLE
meow meow meow meow meow

### ISSUE THREAD

**Issue by Weigurde** [Pissandshittium/pissandshittium#9]
i'm going to eat an sd card with a build of this on it and then shittium it into a skibidi toilet

**Comment by AdamFrack** [comment]
Please dont, instead have the source code on the sd card, as it will increase the

**Comment by itsvic-dev** [comment]
increase what @AdamFrack

**Comment by ialsoneedthisforhacs** [comment]
brrrrr skibidi dop dop dop dop yes yes yes yes

**Comment by AdamFrack** [comment]
> increase what @AdamFrack

It will increase the

**Comment by Techman69** [comment]
I believe the world needs more the

**Comment by Jazztache** [comment]
hmm yes more the

**Comment by aggregate1166877** [comment]
![lol average lol](https://github.com/Pissandshittium/pissandshittium/assets/5172011/66e27c9f-a6eb-4cef-82b5-13bab744a3b1)
